name: flutter_ride_sharing
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.5
  geolocator: ^9.0.2
  flutter_polyline_points: ^1.0.0
  flutter_map: ^3.1.0
  dio: ^5.0.3
  latlong2: ^0.8.1
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_geocoding: ^0.2.0 # Correct version
  shared_preferences: ^2.1.1 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
